# Generated by Django 5.1.5 on 2025-02-06 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del conductor', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre de la persona', max_length=50)),
                ('celular', models.CharField(help_text='Número de celular', max_length=10)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del programador', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Programadores',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(help_text='Dirección', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trayectos',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('VAN', 'Van'), ('ESTACAS', 'Estacas'), ('MINIVAN', 'Minivan'), ('CAMION', 'Camion')], default='VAN', help_text='Tipo de vehiculo', max_length=10)),
                ('placa', models.CharField(help_text='Placa', max_length=6, primary_key=True, serialize=False)),
                ('hora', models.DateTimeField(help_text='Hora', max_length=10)),
                ('disponibilidad', models.CharField(choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo'), ('VERDE', 'Verde'), ('ROJO', 'Rojo')], default='INACTIVO', help_text='Disponibilidad', max_length=10)),
                ('mecanico', models.BooleanField(default=False)),
                ('restaurante', models.BooleanField(default=False)),
                ('enfermo', models.BooleanField(default=False)),
                ('conductor', models.ForeignKey(help_text='Nombre del conductor', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='elim.conductor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medio_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], default='CONTADO', help_text='Medio de pago', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9)),
                ('celular', models.CharField(help_text='Número de celular', max_length=10)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=9)),
                ('neto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('status', models.CharField(choices=[('ejecutado', 'Ejecutado'), ('cotizado', 'Cotizado'), ('facturado', 'Facturado'), ('no_show', 'NO SHOW')], default='cotizado', help_text='Status', max_length=15)),
                ('cotizacion', models.DecimalField(decimal_places=2, max_digits=9)),
                ('factura', models.CharField(help_text='Factura', max_length=50)),
                ('legalizado', models.CharField(choices=[('sin legalizar', 'Sin legalizar'), ('legalizado', 'Legalizado')], default='sin legalizar', help_text='Legalizado', max_length=15)),
                ('cliente', models.ForeignKey(help_text='Nombre del cliente', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='elim.cliente')),
                ('conductor', models.ForeignKey(help_text='Nombre del conductor', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='elim.conductor')),
                ('programador', models.ForeignKey(help_text='Programador', on_delete=django.db.models.deletion.CASCADE, to='elim.programador')),
                ('solicitado_por', models.ForeignKey(help_text='Solicitado por', on_delete=django.db.models.deletion.CASCADE, to='elim.persona')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trayecto', models.ForeignKey(help_text='Dirección de trayecto', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='elim.trayecto')),
                ('placa', models.ForeignKey(help_text='Placa', on_delete=django.db.models.deletion.CASCADE, to='elim.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
    ]
