# Generated by Django 5.1.6 on 2025-02-23 02:42

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(blank=True, max_length=500, null=True, verbose_name='Club')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('zipcode', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad')),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('adress', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('lat', models.CharField(blank=True, max_length=200, null=True)),
                ('lng', models.CharField(blank=True, max_length=200, null=True)),
                ('place_id', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Pais')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del conductor', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conductores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Distances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(blank=True, max_length=200, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_mins', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_traffic_mins', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('from_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='elim.locations')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='elim.locations')),
            ],
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre Museo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.pais')),
            ],
            options={
                'verbose_name': 'Museo',
                'verbose_name_plural': 'Museos',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre de la persona', max_length=50)),
                ('celular', models.CharField(help_text='Número de celular', max_length=10)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del programador', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Programadores',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=50)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('zipcode', models.CharField(max_length=6, verbose_name='Código postal')),
                ('ciudad', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad')),
                ('pais', models.CharField(blank=True, max_length=200, null=True, verbose_name='Pais')),
                ('lat', models.CharField(blank=True, max_length=200, null=True, verbose_name='Latitud')),
                ('lng', models.CharField(blank=True, max_length=200, null=True, verbose_name='Longitud')),
                ('club', models.CharField(blank=True, max_length=500, null=True, verbose_name='Club')),
                ('place_id', models.CharField(blank=True, max_length=200, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Trayectos',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('VAN', 'Van'), ('ESTACAS', 'Estacas'), ('MINIVAN', 'Minivan'), ('CAMION', 'Camion')], default='VAN', max_length=10)),
                ('placa', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('hora', models.DateTimeField(default=datetime.datetime(2025, 2, 22, 21, 42, 47, 185808), max_length=20)),
                ('disponibilidad', models.CharField(choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo'), ('VERDE', 'Verde'), ('ROJO', 'Rojo')], default='INACTIVO', max_length=10)),
                ('mecanico', models.BooleanField(default=False)),
                ('restaurante', models.BooleanField(default=False)),
                ('enfermo', models.BooleanField(default=False)),
                ('conductor', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.PROTECT, to='elim.conductor')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='elim.trayecto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('numero_registo', models.UUIDField(default=uuid.uuid4)),
                ('medio_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], default='CONTADO', max_length=15, verbose_name='Medio de peago')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('celular', models.CharField(max_length=10)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('status', models.CharField(choices=[('creado', 'Creado'), ('ejecutado', 'Ejecutado'), ('cotizado', 'Cotizado'), ('facturado', 'Facturado'), ('no_show', 'NO SHOW')], default='creado', help_text='Status', max_length=15)),
                ('cotizacion', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9)),
                ('factura', models.CharField(blank=True, help_text='Factura', max_length=50)),
                ('legalizado', models.CharField(choices=[('sin legalizar', 'Sin legalizar'), ('legalizado', 'Legalizado')], default='sin legalizar', help_text='Legalizado', max_length=15)),
                ('cliente', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='elim.cliente')),
                ('programador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.programador')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.persona')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trayecto', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='elim.trayecto')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numero_registo', models.UUIDField(default=uuid.uuid4)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 22, 21, 42, 47, 193813), null=True)),
                ('celular', models.CharField(max_length=10)),
                ('medio_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], default='CONTADO', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('neto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elim.cliente')),
                ('solicitado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elim.persona')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trayecto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elim.trayecto')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elim.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='PerfilConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Perfil de conductores',
            },
        ),
    ]
