# Generated by Django 5.1.6 on 2025-03-09 03:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GastoConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('numero_registro', models.UUIDField(default=uuid.uuid4)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('concepto', models.CharField(choices=[('gasolina', 'Gasolina'), ('peaje', 'Peajes'), ('otro', 'Otro')], default='gasolina', max_length=15)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('chip', 'Chip')], default='efectivo', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(10000)])),
                ('placa', models.CharField(max_length=6)),
                ('cedula', models.IntegerField()),
                ('conductor', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(upload_to='gastos')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='elim.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Gastos del conductor',
            },
        ),
    ]
