# Generated by Django 5.1.5 on 2025-02-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='conductor',
        ),
    ]
