# Generated by Django 5.1.5 on 2025-02-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0002_remove_servicio_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cotizacion',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='factura',
            field=models.CharField(blank=True, help_text='Factura', max_length=50),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
