# Generated by Django 5.1.6 on 2025-03-10 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0004_alter_parametro_uc_alter_parametro_um'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='user',
        ),
    ]
