# Generated by Django 5.1.6 on 2025-02-28 04:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0004_alter_registro_fecha_alter_vehiculo_hora_gastos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 27, 23, 40, 43, 995151), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 27, 23, 40, 43, 988631), max_length=20),
        ),
        migrations.CreateModel(
            name='GastoConductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 27, 23, 40, 43, 997151), null=True)),
                ('concepto', models.CharField(choices=[('gasolina', 'Gasolina'), ('peaje', 'Peajes'), ('otro', 'Otro')], default='gasolina', max_length=15)),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('chip', 'Chip')], default='efectivo', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('photo', models.ImageField(upload_to='cars')),
                ('specs', models.FileField(upload_to='specs')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.vehiculo')),
            ],
            options={
                'verbose_name_plural': 'Gastos del conductor',
            },
        ),
        migrations.DeleteModel(
            name='Gastos',
        ),
    ]
