# Generated by Django 5.1.5 on 2025-02-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0005_alter_servicio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='fecha',
        ),
    ]
