# Generated by Django 5.1.6 on 2025-02-28 05:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0005_alter_registro_fecha_alter_vehiculo_hora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 0, 0, 58, 277002), null=True),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='photo',
            field=models.ImageField(upload_to='gastos'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 0, 0, 58, 274993), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 0, 0, 58, 272010), max_length=20),
        ),
    ]
