# Generated by Django 5.1.6 on 2025-02-28 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0006_alter_gastoconductor_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastoconductor',
            old_name='photo',
            new_name='imagen',
        ),
        migrations.AddField(
            model_name='gastoconductor',
            name='conductor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 10, 55, 50, 857967), null=True),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='specs',
            field=models.FileField(blank=True, null=True, upload_to='specs'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 10, 55, 50, 854968), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 10, 55, 50, 849953), max_length=20),
        ),
    ]
