# Generated by Django 5.1.6 on 2025-03-11 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0006_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='registro',
        ),
        migrations.AlterField(
            model_name='viaje',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='elim.registro'),
        ),
    ]
