# Generated by Django 5.1.5 on 2025-02-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0007_servicio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
