# Generated by Django 5.1.6 on 2025-03-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0007_remove_viaje_registro_alter_viaje_to_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='distance_km_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='duration_mins_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='viaje',
            name='duration_traffic_mins_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
