# Generated by Django 5.1.6 on 2025-02-28 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0008_alter_gastoconductor_fecha_alter_registro_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gastoconductor',
            name='specs',
        ),
        migrations.RemoveField(
            model_name='gastoconductor',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='gastoconductor',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gastoconductor',
            name='placa',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 16, 51, 45, 577390), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 16, 51, 45, 574380), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 16, 51, 45, 569883), max_length=20),
        ),
    ]
