# Generated by Django 5.1.6 on 2025-03-14 22:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0008_viaje_distance_km_text_viaje_duration_mins_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoconductor',
            name='descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
