# Generated by Django 5.1.5 on 2025-02-08 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0008_alter_servicio_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
