# Generated by Django 5.1.6 on 2025-03-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0009_gastoconductor_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoconductor',
            name='factura',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
