# Generated by Django 5.1.5 on 2025-02-08 20:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0009_alter_servicio_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='numero_registo',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
