# Generated by Django 5.1.6 on 2025-03-14 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0010_gastoconductor_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoconductor',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(10000)]),
        ),
    ]
