# Generated by Django 5.1.5 on 2025-02-08 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0010_servicio_numero_registo_alter_servicio_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='numero_registo',
        ),
    ]
