# Generated by Django 5.1.5 on 2025-02-08 20:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0011_remove_servicio_numero_registo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='numero_registo',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
