# Generated by Django 5.1.6 on 2025-03-15 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0011_alter_gastoconductor_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoconductor',
            name='credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='gastoconductor',
            name='efectivo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='gastoconductor',
            name='estado_aceptacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gastoconductor',
            name='transferencia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AddField(
            model_name='gastoconductor',
            name='usuario_aceptacion',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gastoconductor',
            name='usuario_rechazo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='medio_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHIP', 'Chip')], default='CONTADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='registro',
            name='medio_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHIP', 'Chip')], default='CONTADO', max_length=15),
        ),
    ]
