# Generated by Django 5.1.6 on 2025-02-28 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0013_gastoconductor_numero_registo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gastoconductor',
            old_name='numero_registo',
            new_name='numero_registro',
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 17, 29, 59, 429178), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 17, 29, 59, 426882), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 17, 29, 59, 421073), max_length=20),
        ),
    ]
