# Generated by Django 5.1.5 on 2025-02-09 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0014_alter_servicio_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Pais')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.AlterField(
            model_name='servicio',
            name='celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cliente',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='elim.cliente'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='medio_pago',
            field=models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], default='CONTADO', max_length=15),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.vehiculo'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='programador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.programador'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.persona'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='trayecto',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='elim.trayecto'),
        ),
        migrations.CreateModel(
            name='Museo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre Museo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elim.pais')),
            ],
            options={
                'verbose_name': 'Museo',
                'verbose_name_plural': 'Museos',
            },
        ),
    ]
