# Generated by Django 5.1.6 on 2025-02-28 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0014_rename_numero_registo_gastoconductor_numero_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoconductor',
            name='cedula',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 17, 34, 37, 93343), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 17, 34, 37, 90347), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 17, 34, 37, 82952), max_length=20),
        ),
    ]
