# Generated by Django 5.1.6 on 2025-03-01 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0015_alter_gastoconductor_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 19, 57, 46, 467), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 19, 57, 45, 999462), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 19, 57, 45, 996437), max_length=20),
        ),
    ]
