# Generated by Django 5.1.6 on 2025-03-01 04:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0016_alter_gastoconductor_fecha_alter_registro_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='cedula',
            field=models.BigIntegerField(blank=True, help_text='Cédula', null=True),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='cedula',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 23, 3, 35, 146401), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 23, 3, 35, 144405), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 23, 3, 35, 135312), max_length=20),
        ),
    ]
