# Generated by Django 5.1.5 on 2025-02-12 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0016_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='fc',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='fm',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='uc',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='um',
        ),
    ]
