# Generated by Django 5.1.5 on 2025-02-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0017_remove_registro_estado_remove_registro_fc_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
