# Generated by Django 5.1.6 on 2025-03-01 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0017_conductor_cedula_alter_gastoconductor_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 23, 8, 25, 145344), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 23, 8, 25, 142326), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 23, 8, 25, 136438), max_length=20),
        ),
    ]
