# Generated by Django 5.1.6 on 2025-03-01 04:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0018_alter_gastoconductor_fecha_alter_registro_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastoconductor',
            name='vehiculo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elim.vehiculo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 23, 26, 36, 42204), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 28, 23, 26, 36, 40204), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 28, 23, 26, 36, 30786), max_length=20),
        ),
    ]
