# Generated by Django 5.1.6 on 2025-02-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0019_registro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='programador',
        ),
    ]
