# Generated by Django 5.1.6 on 2025-03-01 06:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0020_alter_gastoconductor_fecha_alter_registro_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 1, 1, 51, 18, 129403), null=True),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='valor',
            field=models.IntegerField(max_length=10, validators=[django.core.validators.MaxValueValidator(9999999.99)]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 1, 1, 51, 18, 124075), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 1, 51, 18, 118533), max_length=20),
        ),
    ]
