# Generated by Django 5.1.6 on 2025-02-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0021_locations_distances'),
    ]

    operations = [
        migrations.AddField(
            model_name='trayecto',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='club',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Club'),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pais'),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='lat',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Latitud'),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='longitud'),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='place_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='trayecto',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='club',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Club'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
    ]
