# Generated by Django 5.1.6 on 2025-02-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0022_trayecto_address_trayecto_city_trayecto_club_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trayecto',
            name='lng',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Longitud'),
        ),
    ]
