# Generated by Django 5.1.6 on 2025-02-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0023_alter_trayecto_lng'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trayecto',
            old_name='city',
            new_name='ciudad',
        ),
        migrations.RenameField(
            model_name='trayecto',
            old_name='country',
            new_name='pais',
        ),
        migrations.RemoveField(
            model_name='trayecto',
            name='address',
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
    ]
