# Generated by Django 5.1.6 on 2025-03-02 22:01

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0023_alter_gastoconductor_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 2, 17, 1, 29, 38623), null=True),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, max_length=12, validators=[django.core.validators.MaxValueValidator(1000000), django.core.validators.MinValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='vehiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='elim.vehiculo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 2, 17, 1, 29, 35623), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='neto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 17, 1, 29, 30590), max_length=20),
        ),
    ]
