# Generated by Django 5.1.6 on 2025-03-03 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0024_alter_gastoconductor_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='latitud',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='registro',
            name='longitud',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 2, 23, 7, 1, 211380), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 2, 23, 7, 1, 209399), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='neto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 23, 7, 1, 199271), max_length=20),
        ),
    ]
