# Generated by Django 5.1.6 on 2025-02-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0025_alter_servicio_medio_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='disponibilidad',
            field=models.CharField(choices=[('INACTIVO', 'Inactivo'), ('ACTIVO', 'Activo'), ('VERDE', 'Verde'), ('ROJO', 'Rojo')], default='INACTIVO', max_length=10),
        ),
    ]
