# Generated by Django 5.1.6 on 2025-03-03 04:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0025_registro_direccion_registro_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoconductor',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 2, 23, 7, 26, 62130), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 2, 23, 7, 26, 58135), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 2, 23, 7, 26, 50069), max_length=20),
        ),
    ]
