# Generated by Django 5.1.6 on 2025-02-18 20:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0027_alter_registro_fecha'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='conductor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Conductores'},
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 18, 15, 59, 42, 319025), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(help_text='Nombre del conductor', max_length=50, on_delete=django.db.models.deletion.RESTRICT, to='elim.conductor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 15, 59, 42, 317517), help_text='Hora', max_length=20),
        ),
    ]
