# Generated by Django 5.1.6 on 2025-02-18 21:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0028_alter_cliente_options_alter_conductor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 18, 16, 14, 37, 169639), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='conductor',
            field=models.ForeignKey(help_text='Nombre del conductor', max_length=50, on_delete=django.db.models.deletion.PROTECT, to='elim.conductor'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 16, 14, 37, 167634), help_text='Hora', max_length=20),
        ),
    ]
