# Generated by Django 5.1.6 on 2025-02-18 21:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0029_alter_registro_fecha_alter_vehiculo_conductor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cliente',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.RESTRICT, to='elim.cliente'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 18, 16, 20, 41, 141220), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='elim.vehiculo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='elim.persona'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='trayecto',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.RESTRICT, to='elim.trayecto'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 16, 20, 41, 140221), help_text='Hora', max_length=20),
        ),
    ]
