# Generated by Django 5.1.6 on 2025-02-19 00:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0030_alter_registro_cliente_alter_registro_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 18, 19, 48, 11, 805314), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 19, 48, 11, 801484), help_text='Hora', max_length=20),
        ),
    ]
