# Generated by Django 5.1.6 on 2025-02-19 01:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0031_alter_registro_fecha_alter_vehiculo_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 18, 20, 46, 4, 506893), null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 20, 46, 4, 505033), help_text='Hora', max_length=20),
        ),
    ]
