# Generated by Django 5.1.6 on 2025-02-19 02:21

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0032_alter_registro_fecha_alter_vehiculo_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='elim.cliente'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 18, 21, 21, 47, 532081), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='trayecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='elim.trayecto'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 21, 21, 47, 528766), help_text='Hora', max_length=20),
        ),
    ]
