# Generated by Django 5.1.6 on 2025-02-19 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0033_alter_registro_cliente_alter_registro_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 13, 52, 14, 475716), null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 13, 52, 14, 471120), help_text='Hora', max_length=20),
        ),
    ]
