# Generated by Django 5.1.6 on 2025-02-19 18:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0034_alter_registro_fecha_alter_trayecto_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elim.cliente'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 13, 52, 58, 212255), null=True),
        ),
        migrations.AlterField(
            model_name='registro',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elim.vehiculo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='solicitado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elim.persona'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='trayecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='elim.trayecto'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 13, 52, 58, 207236), help_text='Hora', max_length=20),
        ),
    ]
