# Generated by Django 5.1.6 on 2025-02-19 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0035_alter_registro_cliente_alter_registro_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 17, 53, 44, 306850), null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='zipcode',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 17, 53, 44, 303358), help_text='Hora', max_length=20),
        ),
    ]
