# Generated by Django 5.1.6 on 2025-02-19 22:59

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0038_alter_registro_fecha_alter_trayecto_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 17, 59, 36, 293351), null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='zipcode',
            field=models.IntegerField(blank=True, max_length=6, null=True, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100)], verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 17, 59, 36, 290357), help_text='Hora', max_length=20),
        ),
    ]
