# Generated by Django 5.1.6 on 2025-02-20 00:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0042_alter_registro_fecha_alter_trayecto_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 19, 19, 58, 48, 598114), null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='zipcode',
            field=models.DecimalField(decimal_places=0, max_digits=6, validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(100)], verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 19, 58, 48, 594586), help_text='Hora', max_length=20),
        ),
    ]
