# Generated by Django 5.1.6 on 2025-02-20 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elim', '0048_alter_registro_fecha_alter_trayecto_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='fecha',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 2, 20, 0, 53, 30, 373909), null=True),
        ),
        migrations.AlterField(
            model_name='trayecto',
            name='zipcode',
            field=models.CharField(max_length=6, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='hora',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 0, 53, 30, 370399), help_text='Hora', max_length=20),
        ),
    ]
